FROM node:20-alpine AS build
WORKDIR /app

RUN corepack enable

COPY webui/package.json webui/yarn.lock webui/.yarnrc.yml ./
COPY webui/.yarn ./.yarn

RUN corepack use yarn@4.5.0

RUN yarn install --immutable

COPY webui ./ 
RUN yarn run build-prod

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
