FROM golang:1.21-alpine AS build
WORKDIR /src

#toolchain e header SQLite per cgo
RUN apk add --no-cache build-base sqlite-dev

# dipendenze Go
COPY go.mod go.sum ./
RUN go mod download

# sorgenti
COPY . .

#build
RUN CGO_ENABLED=1 go build -o /out/webapi ./cmd/webapi

# run
FROM alpine:3.20
WORKDIR /app

RUN apk add --no-cache sqlite-libs ca-certificates

COPY --from=build /out/webapi /app/webapi
EXPOSE 8080
ENV PORT=8080
CMD ["/app/webapi"]
