openapi: 3.0.3 
servers:
  - url: "http://localhost:3000/v1"
info:
  title: WASAText API
  description: WASAText - Messaging app API spec for WASA course
  version: "1.0.0"

tags:
  - name: login
    description: Endpoints for user loggin and authentication
  - name: profile
    description: Endpoints for editing user profile (name, photo)
  - name: conversations 
    description: Endpoints for listing and retrieving conversations
  - name: messages
    description: Endpoints for sending, commententing, forwarding and deleting messages
  - name: groups
    description: Endpoints for managing group membership and info

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"

  /me/username:
    put:
      tags: ["profile"]
      operationId: setMyUserName
      summary: Change user display name
      description: Change your display name
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "NewName"
      responses:
        '200':
          description: Name changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: 
                    type: string 
              example:
                name: "NewName"
        '401':
          { $ref: '#/components/responses/Unauthorized' }
        '404':
          { $ref: '#/components/responses/NotFound' }
        '400':
          { $ref: '#/components/responses/BadRequest' }
 
  /me/photo:
    put:
      tags: ["profile"]
      operationId: setMyPhoto
      summary: Upload or update user profile photo 
      security: 
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema: 
              type: object
              properties:
                photo:
                  type: string 
                  format: binary
      responses:
        '200':
          description: Photo uploaded
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }

  /me/conversations:
    get:
      tags: ["conversations"]
      operationId: getMyConversations
      summary: Get all conversations for the current user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of conversations returned 
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }
  
  /conversations/{id}:
    get:
      tags: ["conversations"]
      operationId: getConversation 
      summary: Get full conversation by id
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the resource
      responses:
        '200':
          description: conversation returned 
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Conversation id 
                  partecipants:
                    type: array
                    items:
                      type: string
                      description: Names of partecipants
                  messages:
                    type: array
                    description: List of messages
                    items:
                      type: object
                      properties:
                        sender:
                          type: string
                        text: 
                          type: string
                        timestamp:
                          type: string
                          format: date-time
              example:
                id: "emanuele99"
                partecipants: ["Marco", "Maria"]
                messages:
                  - sender: "Maria"
                    text: "Ciao"
                    timestamp: "2025-07-28T12:00:00Z"
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }

  /conversations/{id}/messages:
    post:
      tags: ["messages"]
      operationId: sendMessage
      summary: Send a new message
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier 

      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  example: "Hey, how you doin?"
                timestamp:
                  type: string
                  format: date-time
                  example: "2025-07-28T15:45:00Z"
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageId:
                    type: string
                  status:
                    type: string
              example:
                messageId: "msg123"
                status: "sent"
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }
  
  /messages/{id}/forward:
    post:
      tags: ["messages"]
      operationId: forwardMessage
      summary: Forward a message to another conversation
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string   
          description: Unique identifier of the resource
          
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - conversationId
              properties:
                conversationId:
                  type: string
                  example: "124u8429djnkf"
      responses:
        '200':
          description: Message forwarded
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }
 
  /messages/{id}/comments:
    post:
      tags: ["messages"]
      operationId: commentMessage
      summary: Add a reaction to message
      security:
        - BearerAuth: []
      parameters:
        - name: id 
          in: path
          required: true
          schema: 
            type: string
          description: Unique identifier of the resource

      responses:
        '200':
          description: Comment added
          content:
            application/json:
              schema:
                type: object
                properties:
                  commentId:
                    type: string
                  status:
                    type: string 
              example:
                commentId: "cmt001"
                status: "ok"
        '401':
          { $ref: '#/components/responses/Unauthorized' }
        '404':
          { $ref: '#/components/responses/NotFound' }
        '400':
          { $ref: '#/components/responses/BadRequest' }
    delete:
      tags: ["messages"]
      operationId: uncommentMessage
      summary: Remove a comment from a messsage
      security: 
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the resource
      responses:
          '200':
            description: Comment removed
          '401':
            { $ref: '#/components/responses/Unauthorized' }
          '404':
            { $ref: '#/components/responses/NotFound' }
          '400':
            { $ref: '#/components/responses/BadRequest' }

  /messages/{id}:
    delete:
      tags: ["messages"]
      operationId: deleteMessage
      summary: Delete a message
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the resource
      responses:
        '200':
          description: Message deleted
        '401':
          { $ref: '#/components/responses/Unauthorized' }
        '404':
          { $ref: '#/components/responses/NotFound' }
        '400':
          { $ref: '#/components/responses/BadRequest' }

  /groups/{id}/members:
    post:
      tags: ["groups"]
      operationId: addToGroup
      summary: Add user to a group 
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the resource
      responses:
        '200':
          description: User added to a group
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }
    delete:
      tags: ["groups"]
      operationId: leaveGroup
      summary: Leave a group 
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the resource
      responses:
        '200':
          description: Left group
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }

  /groups/{id}/name:
    put:
      tags: ["groups"]
      operationId: setGroupName
      summary: Change group name 
      security:
        - BearerAuth: []
      parameters:
        - name: id 
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the resource
      responses:
        '200':
          description: User added to a group
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }

  /groups/{id}/photo:
    put:
      tags: ["groups"]
      operationId: setGroupPhoto
      summary: Change group photo 
      security: 
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema: 
              type: object
              properties:
                photo:
                  type: string 
                  format: binary
      parameters:
        - name: id 
          in: path
          required: true
          schema:
            type: string
          description: The group ID
      responses:
        '200':
          description: Group photo uploaded
        '401':
            { $ref: '#/components/responses/Unauthorized' }
        '404':
            { $ref: '#/components/responses/NotFound' }
        '400':
            { $ref: '#/components/responses/BadRequest' }

components:
  responses:
    Unauthorized:
      description: The access token is missing or it's expired
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Not authorized"
    BadRequest:
      description: The request was not compliant with the documentation (e.g., missing fields, etc.)
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Bad request"
    NotFound:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Not found"
    Forbidden:
      description: You are not allowed to perform this operation
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Forbiedden operation"

  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Unique user identifier returned at login